name: solar_monitoring
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  dio_cache_interceptor: ^3.5.0
  path_provider: ^2.1.5
  dio_cache_interceptor_hive_store: ^3.2.2
  get_it: ^8.0.2
  monitoring_core:
    path: packages/monitoring_core
  monitoring_models:
    path: packages/monitoring_models  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
