name: monitoring_chart
description: "A new Flutter package project."
version: 0.0.1
publish_to: 'none'
environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  monitoring_core:
    path: ../monitoring_core
  fl_chart: ^0.69.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  coverage: ^1.11.0